language: node_js
node_js:
  - "12"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgnome-keyring-dev
      - libsecret-1-dev
before_script:
  - npm run lint
