# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ニコニコ生放送デスクトップアプリ
description:
  コメントビューアによるコメント表示や放送開始の通知を受け取ることができます
twitter_username: tsuwatch
github_username:  tsuwatch
show_downloads: true
github:
  is_project_page: true
  repository_name: kaizoku
  repository_url: https://github.com/tsuwatch/kaizoku
  zip_url: https://github.com/tsuwatch/kaizoku/releases/download/v0.7.1/Kaizoku-darwin-x64.zip
  owner_name: tsuwatch
  owner_url: https://github.com/tsuwatch

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
